import { DriverProfile, PlatformSettings, UserProfile, Coupon, ComplaintTicket, Ride } from '../types';

export const DEFAULT_PLATFORM_SETTINGS: PlatformSettings = {
  appName: 'EASY TRIP Golaghat',
  supportPhone: '+91 8638803320',
  supportEmail: 'bijaysaikia543@gmail.com',
  emergencySosNumber: '112',
  commissionRatePercent: 15,
  surgePricingEnabled: true,
  surgeMultiplier: 1.0,
  nightChargeMultiplier: 1.2,
  waitingChargePerMin: 2,
  maintenanceMode: false,
  maintenanceMessage: 'EASY TRIP is currently undergoing scheduled platform optimization. We will be back online shortly!',
  driverAdminFeeBikeAuto: 5,
  driverAdminFeeCab: 50,
  adminUpiId: '8638803320@okbizaxis',
  adminUpiName: 'vijay xaikia',
  adminUpiPhone: '+91 86388 03320',
  fares: {
    bike: {
      type: 'bike',
      name: 'EASY Bike (Kaziranga Express)',
      iconName: 'Bike',
      baseFare: 25,
      pricePerKm: 9,
      minimumFare: 25,
      perMinuteRate: 1.0,
      capacity: 1,
      description: 'Quickest solo ride across Bokakhat, Kohora & Golaghat',
    },
    auto: {
      type: 'auto',
      name: 'EASY Auto (Local 3-Seater)',
      iconName: 'Compass',
      baseFare: 35,
      pricePerKm: 13,
      minimumFare: 35,
      perMinuteRate: 1.2,
      capacity: 3,
      description: 'Reliable 3-seater for local market & township travel',
    },
    cab: {
      type: 'cab',
      name: 'EASY Cab / Prime (AC Sedan)',
      iconName: 'Car',
      baseFare: 65,
      pricePerKm: 17,
      minimumFare: 65,
      perMinuteRate: 1.8,
      capacity: 4,
      description: 'Comfortable AC cab for highway & district inter-town trips',
    },
  },
};

export const CONTACT_INFO = {
  mainOffice: 'Main Office: Bokakhat, Golaghat District, State: Assam (PIN 785612)',
  district: 'Golaghat District, Assam',
  email: 'bijaysaikia543@gmail.com',
  helplineNumbers: ['8638803320', '7002754262', '9101876404'],
  primaryHelpline: '+91 8638803320',
  policeEmergency: '112 / Golaghat Control Room',
};

export const GOLAGHAT_TOWNS = [
  { id: 'bokakhat', name: 'Bokakhat', subDivision: 'Bokakhat', role: 'Main Office & Gateway', lat: 26.5925, lng: 93.5937, landmark: 'Bokakhat Main Chariali / NRL Gate, NH-37' },
  { id: 'kohora', name: 'Kohora (Kaziranga)', subDivision: 'Bokakhat', role: 'Kaziranga National Park Main Range', lat: 26.5833, lng: 93.4167, landmark: 'Kohora Tourist Complex / Rhino Gate' },
  { id: 'bagori', name: 'Bagori Range', subDivision: 'Bokakhat', role: 'Kaziranga Western Safari Range', lat: 26.5710, lng: 93.3520, landmark: 'Bagori Safari Entry, NH-37' },
  { id: 'numaligarh', name: 'Numaligarh Tiniali', subDivision: 'Bokakhat', role: 'Refinery & Junction Hub', lat: 26.6347, lng: 93.7431, landmark: 'Numaligarh Tiniali / NRL Township' },
  { id: 'dergaon', name: 'Dergaon', subDivision: 'Dergaon', role: 'Police Training / Town', lat: 26.7011, lng: 93.9723, landmark: 'Dergaon Chariali / Assam Police Academy' },
  { id: 'golaghat-town', name: 'Golaghat Town', subDivision: 'Golaghat Sadar', role: 'District Headquarter', lat: 26.5186, lng: 93.9688, landmark: 'Golaghat Court Field / DC Office' },
  { id: 'bengnakhowa', name: 'Bengnakhowa', subDivision: 'Golaghat Sadar', role: 'Commercial Center & ASTC', lat: 26.5050, lng: 93.9600, landmark: 'Bengnakhowa Chariali, Golaghat' },
  { id: 'furkating', name: 'Furkating Junction', subDivision: 'Golaghat Sadar', role: 'Major Railway Junction', lat: 26.4380, lng: 93.9850, landmark: 'Furkating Railway Station' },
  { id: 'khumtai', name: 'Khumtai', subDivision: 'Golaghat Sadar', role: 'Tea & Agriculture Hub', lat: 26.6120, lng: 93.9240, landmark: 'Khumtai Chariali, Golaghat' },
  { id: 'kamargaon', name: 'Kamargaon', subDivision: 'Bokakhat', role: 'Transit Junction', lat: 26.6210, lng: 93.6820, landmark: 'Kamargaon Chariali, NH-37' },
  { id: 'sarupathar', name: 'Sarupathar', subDivision: 'Dhansiri', role: 'Sub-Divisional Headquarter', lat: 26.1833, lng: 93.8167, landmark: 'Sarupathar Town & Railway Station' },
  { id: 'barpathar', name: 'Barpathar', subDivision: 'Dhansiri', role: 'Agricultural Hub', lat: 26.3012, lng: 93.8645, landmark: 'Barpathar Town Bus Stand' },
  { id: 'bokajan', name: 'Bokajan', subDivision: 'Dhansiri', role: 'Border Transit Hub', lat: 26.0167, lng: 93.7833, landmark: 'Bokajan Railway Station / Cement Factory' },
  { id: 'negheriting', name: 'Negheriting', subDivision: 'Dergaon', role: 'Historic Heritage Doul', lat: 26.7210, lng: 93.9520, landmark: 'Negheriting Shiva Doul, Dergaon' },
  { id: 'morongi', name: 'Morongi', subDivision: 'Golaghat Sadar', role: 'Tea Estate Corridor', lat: 26.5320, lng: 93.8120, landmark: 'Morongi Tea Estate / Purabangla' },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-cust-1',
    name: 'Ankur Saikia',
    email: 'ankursaikia543@gmail.com',
    phone: '+91 86388 03320',
    role: 'customer',
    status: 'active',
    walletBalance: 450,
    emergencyContact: '+91 70027 54262',
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'user-drv-1',
    name: 'Pranjal Bora',
    email: 'pranjal.driver@easytrip.in',
    phone: '+91 70027 54262',
    role: 'driver',
    status: 'active',
    walletBalance: 1280,
    emergencyContact: '+91 91018 76404',
    createdAt: '2025-01-12T11:00:00Z',
    updatedAt: '2025-01-12T11:00:00Z',
  },
  {
    id: 'user-admin-1',
    name: 'Bijay Saikia (Super Admin)',
    email: 'bijaysaikia543@gmail.com',
    phone: '+91 86388 03320',
    role: 'admin',
    status: 'active',
    walletBalance: 0,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
];

export const INITIAL_DRIVERS: DriverProfile[] = [
  {
    id: 'drv-profile-1',
    userId: 'user-drv-1',
    name: 'Pranjal Bora',
    phone: '+91 70027 54262',
    email: 'pranjal.driver@easytrip.in',
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    vehicleType: 'cab',
    vehicleBrand: 'Maruti Suzuki',
    vehicleModel: 'Dzire Tour',
    vehicleColor: 'Silky Silver',
    vehicleNumber: 'AS 05 C 4421',
    licenseNumber: 'AS-0520210034567',
    documents: {
      licenseUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&auto=format&fit=crop&q=80',
      rcBookUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
      insuranceUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=400&auto=format&fit=crop&q=80',
      submittedAt: '2025-01-12T11:30:00Z',
    },
    approvalStatus: 'approved',
    onlineStatus: 'online',
    availabilityStatus: 'available',
    currentLocation: {
      address: 'Bokakhat Main Chariali, NH-37, Assam',
      lat: 26.5925,
      lng: 93.5937,
      city: 'Bokakhat',
    },
    rating: 4.92,
    totalRatingsCount: 168,
    totalRides: 215,
    todayEarnings: 1650,
    totalEarnings: 48900,
    platformCommissionRate: 0.15,
    welfare: {
      hasEpfo: true,
      epfoUan: '101293847562',
      epfoMemberId: 'AS/GHY/0084729/000/1012938',
      epfoStatus: 'verified',
      epfoRegisteredDate: '2025-01-20',
      epfoNomineeName: 'Maini Bora (Wife)',
      epfoNomineeRelation: 'Spouse',
      monthlyPfAccumulation: 2450,
      hasEsic: true,
      esicIpNumber: '1329485760',
      esicStatus: 'verified',
      esicRegisteredDate: '2025-01-20',
      esicDispensary: 'ESIC Dispensary, Golaghat Town / Bokakhat Model Hospital',
      esicMedicalCoverageLimit: 500000,
      aadhaarNumber: 'XXXX-XXXX-8921',
      panNumber: 'ABCDE1234F',
      bankAccountNo: '50100492182736',
      bankIfsc: 'HDFC0001827',
      bankName: 'HDFC Bank Bokakhat Branch',
    },
    createdAt: '2025-01-12T11:00:00Z',
  },
  {
    id: 'drv-profile-2',
    userId: 'user-drv-2',
    name: 'Bikash Gogoi',
    phone: '+91 91018 76404',
    email: 'bikash.gogoi@easytrip.in',
    photoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    vehicleType: 'auto',
    vehicleBrand: 'Bajaj',
    vehicleModel: 'Maxima Green',
    vehicleColor: 'Yellow & Green',
    vehicleNumber: 'AS 05 R 1928',
    licenseNumber: 'AS-0520190045231',
    documents: {
      submittedAt: '2025-01-15T09:15:00Z',
    },
    approvalStatus: 'approved',
    onlineStatus: 'online',
    availabilityStatus: 'available',
    currentLocation: {
      address: 'Golaghat Court Field, Golaghat Town',
      lat: 26.5186,
      lng: 93.9688,
      city: 'Golaghat Town',
    },
    rating: 4.85,
    totalRatingsCount: 112,
    totalRides: 145,
    todayEarnings: 1120,
    totalEarnings: 33400,
    platformCommissionRate: 0.15,
    welfare: {
      hasEpfo: true,
      epfoUan: '101948572619',
      epfoMemberId: 'AS/GHY/0084729/000/1019485',
      epfoStatus: 'verified',
      epfoRegisteredDate: '2025-01-25',
      epfoNomineeName: 'Rina Gogoi (Mother)',
      epfoNomineeRelation: 'Mother',
      monthlyPfAccumulation: 1820,
      hasEsic: true,
      esicIpNumber: '1394820194',
      esicStatus: 'verified',
      esicRegisteredDate: '2025-01-25',
      esicDispensary: 'ESIC Dispensary, Golaghat Civil Hospital',
      esicMedicalCoverageLimit: 500000,
      aadhaarNumber: 'XXXX-XXXX-4512',
      panNumber: 'BKPG1234K',
      bankAccountNo: '30291847562',
      bankIfsc: 'SBIN0000083',
      bankName: 'SBI Golaghat Main Branch',
    },
    createdAt: '2025-01-15T09:00:00Z',
  },
  {
    id: 'drv-profile-3',
    userId: 'user-drv-3',
    name: 'Mintu Hazarika',
    phone: '+91 86388 03320',
    email: 'mintu.bike@easytrip.in',
    photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    vehicleType: 'bike',
    vehicleBrand: 'Hero',
    vehicleModel: 'Glamour 125',
    vehicleColor: 'Black & Orange',
    vehicleNumber: 'AS 05 T 6723',
    licenseNumber: 'AS-0520200088192',
    documents: {
      submittedAt: '2025-01-18T14:00:00Z',
    },
    approvalStatus: 'approved',
    onlineStatus: 'online',
    availabilityStatus: 'available',
    currentLocation: {
      address: 'Kohora Tourist Complex, Kaziranga',
      lat: 26.5833,
      lng: 93.4167,
      city: 'Kohora',
    },
    rating: 4.96,
    totalRatingsCount: 194,
    totalRides: 280,
    todayEarnings: 890,
    totalEarnings: 39500,
    platformCommissionRate: 0.15,
    welfare: {
      hasEpfo: true,
      epfoUan: '101837492015',
      epfoMemberId: 'AS/GHY/0084729/000/1018374',
      epfoStatus: 'verified',
      epfoRegisteredDate: '2025-02-01',
      epfoNomineeName: 'Pooja Hazarika (Spouse)',
      epfoNomineeRelation: 'Spouse',
      monthlyPfAccumulation: 1450,
      hasEsic: true,
      esicIpNumber: '1384729105',
      esicStatus: 'verified',
      esicRegisteredDate: '2025-02-01',
      esicDispensary: 'ESIC Dispensary, Kohora / Bokakhat FRU',
      esicMedicalCoverageLimit: 500000,
      aadhaarNumber: 'XXXX-XXXX-9912',
      panNumber: 'MHZK9981P',
      bankAccountNo: '209384710293',
      bankIfsc: 'PUNB0182900',
      bankName: 'PNB Bokakhat Branch',
    },
    createdAt: '2025-01-18T13:45:00Z',
  },
  {
    id: 'drv-profile-4',
    userId: 'user-drv-4',
    name: 'Dipankar Dutta',
    phone: '+91 70027 54262',
    email: 'dipankar.dutta@easytrip.in',
    photoURL: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&auto=format&fit=crop&q=80',
    vehicleType: 'cab',
    vehicleBrand: 'Tata',
    vehicleModel: 'Tigor EV',
    vehicleColor: 'Teal Blue',
    vehicleNumber: 'AS 05 EV 8891',
    licenseNumber: 'AS-0520220091823',
    documents: {
      submittedAt: '2025-02-01T10:00:00Z',
    },
    approvalStatus: 'pending',
    onlineStatus: 'offline',
    availabilityStatus: 'available',
    currentLocation: {
      address: 'Numaligarh Tiniali, NRL Township',
      lat: 26.6347,
      lng: 93.7431,
      city: 'Numaligarh',
    },
    rating: 5.0,
    totalRatingsCount: 0,
    totalRides: 0,
    todayEarnings: 0,
    totalEarnings: 0,
    platformCommissionRate: 0.15,
    createdAt: '2025-02-01T09:30:00Z',
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'GOLAGHAT50',
    description: 'Flat ₹50 OFF on your first ride in Golaghat & Bokakhat',
    discountType: 'flat',
    discountValue: 50,
    minimumFare: 80,
    maximumDiscount: 50,
    expiryDate: '2026-12-31',
    active: true,
    usageCount: 420,
  },
  {
    id: 'coup-2',
    code: 'KAZIRANGA20',
    description: '20% OFF on trips between Kohora, Bokakhat and Numaligarh',
    discountType: 'percentage',
    discountValue: 20,
    minimumFare: 60,
    maximumDiscount: 45,
    expiryDate: '2026-12-31',
    active: true,
    usageCount: 235,
  },
  {
    id: 'coup-3',
    code: 'EASYBOKAKHAT',
    description: '25% OFF on rides to and from Bokakhat Main Office area',
    discountType: 'percentage',
    discountValue: 25,
    minimumFare: 70,
    maximumDiscount: 50,
    expiryDate: '2026-12-31',
    active: true,
    usageCount: 512,
  },
];

export const INITIAL_COMPLAINTS: ComplaintTicket[] = [
  {
    id: 'comp-101',
    userId: 'user-cust-1',
    userName: 'Ankur Saikia',
    userRole: 'customer',
    userPhone: '+91 86388 03320',
    rideId: 'ride-demo-past-1',
    subject: 'Driver took bypass near Numaligarh Refinery',
    category: 'fare_dispute',
    description: 'Driver took the NH-39 bypass instead of the direct route towards Numaligarh. Please verify trip mileage and recalculate.',
    status: 'open',
    createdAt: '2025-02-20T14:20:00Z',
    aiSummary: 'Customer requests fare verification for Bokakhat to Numaligarh route. Recommended: Check GPS corridor logs; refund difference via coupon.',
  },
  {
    id: 'comp-102',
    userId: 'user-cust-2',
    userName: 'Juri Phukan',
    userRole: 'customer',
    userPhone: '+91 70027 54262',
    rideId: 'ride-demo-past-2',
    subject: 'Left shopping bag in cab at Golaghat Town market',
    category: 'lost_item',
    description: 'Accidentally left a gift bag in cab AS 05 C 4421 near Bengnakhowa Chariali.',
    status: 'in_progress',
    adminResponse: 'Driver Pranjal Bora confirmed bag is secured in vehicle boot. Will hand over at Bokakhat office today.',
    createdAt: '2025-02-21T09:10:00Z',
    aiSummary: 'Lost property retrieval (Golaghat). Driver contacted and delivery scheduled at Bokakhat Head Office.',
  }
];

export const INITIAL_RIDES: Ride[] = [
  {
    id: 'ride-demo-past-1',
    customerId: 'user-cust-1',
    customerName: 'Ankur Saikia',
    customerPhone: '+91 86388 03320',
    driverId: 'drv-profile-1',
    driverName: 'Pranjal Bora',
    driverPhone: '+91 70027 54262',
    driverPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    driverRating: 4.92,
    vehicleType: 'cab',
    vehicleBrand: 'Maruti Suzuki',
    vehicleModel: 'Dzire Tour',
    vehicleNumber: 'AS 05 C 4421',
    vehicleColor: 'Silky Silver',
    otp: '4821',
    pickup: {
      address: 'Bokakhat Main Chariali, NH-37, Assam',
      lat: 26.5925,
      lng: 93.5937,
      city: 'Bokakhat',
    },
    destination: {
      address: 'Golaghat Town Court Field, Assam',
      lat: 26.5186,
      lng: 93.9688,
      city: 'Golaghat Town',
    },
    distanceKm: 42.0,
    estimatedDurationMin: 55,
    estimatedFare: 779,
    finalFare: 779,
    status: 'completed',
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    transactionId: 'UPI-AS-984271892',
    createdAt: '2025-02-18T10:15:00Z',
    completedAt: '2025-02-18T11:10:00Z',
    rating: 5,
    review: 'Smooth ride along NH-37 from Bokakhat to Golaghat. Very polite driver.',
  },
  {
    id: 'ride-demo-past-2',
    customerId: 'user-cust-1',
    customerName: 'Ankur Saikia',
    customerPhone: '+91 86388 03320',
    driverId: 'drv-profile-3',
    driverName: 'Mintu Hazarika',
    driverPhone: '+91 86388 03320',
    driverPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    driverRating: 4.96,
    vehicleType: 'bike',
    vehicleBrand: 'Hero',
    vehicleModel: 'Glamour 125',
    vehicleNumber: 'AS 05 T 6723',
    otp: '7392',
    pickup: {
      address: 'Kohora Tourist Complex, Kaziranga',
      lat: 26.5833,
      lng: 93.4167,
      city: 'Kohora',
    },
    destination: {
      address: 'Bokakhat Main Market, Assam',
      lat: 26.5925,
      lng: 93.5937,
      city: 'Bokakhat',
    },
    distanceKm: 18.2,
    estimatedDurationMin: 24,
    estimatedFare: 188,
    finalFare: 188,
    status: 'completed',
    paymentMethod: 'cash',
    paymentStatus: 'paid',
    createdAt: '2025-02-19T16:30:00Z',
    completedAt: '2025-02-19T16:54:00Z',
    rating: 5,
    review: 'Fast bike ride, provided helmet and was on time.',
  }
];

export const GOLAGHAT_BLOCKS = [
  { id: 'all', name: 'All Development Blocks', count: 32 },
  { id: 'bokakhat', name: 'Bokakhat Block', count: 8 },
  { id: 'golaghat_central', name: 'Golaghat Central / Sadar', count: 8 },
  { id: 'dergaon', name: 'Dergaon Block', count: 6 },
  { id: 'morongi', name: 'Morongi Block', count: 4 },
  { id: 'padumoni', name: 'Padumoni Block', count: 3 },
  { id: 'sarupathar', name: 'Sarupathar / Dhansiri Block', count: 6 },
  { id: 'gomariguri', name: 'Gomariguri / Merapani Block', count: 3 },
];

export interface GaonPanchayat {
  id: string;
  name: string;
  block: string;
  blockName: string;
  headquarter: string;
  lat: number;
  lng: number;
  villages: string[];
  keyLandmarks: string;
}

export const GOLAGHAT_GAON_PANCHAYATS: GaonPanchayat[] = [
  // Bokakhat Block
  {
    id: 'gp-kohora',
    name: 'Kohora Gaon Panchayat',
    block: 'bokakhat',
    blockName: 'Bokakhat Block',
    headquarter: 'Kohora Chariali',
    lat: 26.5833,
    lng: 93.4167,
    villages: ['Kohora Gaon', 'Diring Gaon', 'Bagori Village', 'Halflong Gaon', 'Siljuri'],
    keyLandmarks: 'Kaziranga Safari Gate, Orchid Park, Rhino Complex NH-37',
  },
  {
    id: 'gp-diffloo',
    name: 'Diffloo Pathar Gaon Panchayat',
    block: 'bokakhat',
    blockName: 'Bokakhat Block',
    headquarter: 'Diffloo Tiniali',
    lat: 26.5880,
    lng: 93.4920,
    villages: ['Diffloo Pathar', 'Bholaguri Gaon', 'Mohpara Village', 'Borchapori'],
    keyLandmarks: 'Bholaguri Tea Estate, Diffloo River Bridge',
  },
  {
    id: 'gp-pub-bokakhat',
    name: 'Pub Bokakhat Gaon Panchayat',
    block: 'bokakhat',
    blockName: 'Bokakhat Block',
    headquarter: 'Bokakhat Main Town',
    lat: 26.5925,
    lng: 93.5937,
    villages: ['Bokakhat Gaon', 'Natun Gaon', 'Kumalia Gaon', 'Rajabari Gaon'],
    keyLandmarks: 'Bokakhat Main Chariali, NRL Gate, Sub-Divisional Office',
  },
  {
    id: 'gp-paschim-bokakhat',
    name: 'Paschim Bokakhat Gaon Panchayat',
    block: 'bokakhat',
    blockName: 'Bokakhat Block',
    headquarter: 'Behora Chariali',
    lat: 26.5750,
    lng: 93.5350,
    villages: ['Behora Gaon', 'Panbari Village', 'Borjuri Gaon', 'Bongaon'],
    keyLandmarks: 'Behora Tea Estate, Panbari Reserve',
  },
  {
    id: 'gp-numaligarh',
    name: 'Numaligarh Gaon Panchayat',
    block: 'bokakhat',
    blockName: 'Bokakhat Block',
    headquarter: 'Numaligarh Tiniali',
    lat: 26.6347,
    lng: 93.7431,
    villages: ['Numaligarh Gaon', 'Telgaram', 'Rajabari', 'Deopahar Gaon'],
    keyLandmarks: 'NRL Refinery Gate, Deopahar Heritage Site, NH-39 Junction',
  },
  {
    id: 'gp-kamargaon',
    name: 'Kamargaon Gaon Panchayat',
    block: 'bokakhat',
    blockName: 'Bokakhat Block',
    headquarter: 'Kamargaon Chariali',
    lat: 26.6210,
    lng: 93.6820,
    villages: ['Kamargaon', 'Dagaon', 'Borbari', 'Bokakhat Pathar'],
    keyLandmarks: 'Kamargaon College & Market, NH-37 Corridor',
  },
  {
    id: 'gp-kurwabahi',
    name: 'Kurwabahi Gaon Panchayat',
    block: 'bokakhat',
    blockName: 'Bokakhat Block',
    headquarter: 'Kurwabahi Satra',
    lat: 26.6450,
    lng: 93.6210,
    villages: ['Kurwabahi Gaon', 'Borting', 'Dighali Pathar', 'Salmora'],
    keyLandmarks: 'Historic Kurwabahi Satra, River Island Road',
  },
  {
    id: 'gp-mohpora',
    name: 'Mohpora Gaon Panchayat',
    block: 'bokakhat',
    blockName: 'Bokakhat Block',
    headquarter: 'Mohpora Center',
    lat: 26.6020,
    lng: 93.6620,
    villages: ['Mohpora Gaon', 'Gohain Gaon', 'Kakatigaon'],
    keyLandmarks: 'Mohpora High School & Rural Health Center',
  },

  // Golaghat Central / Sadar Block
  {
    id: 'gp-golaghat-town',
    name: 'Golaghat Town & DC Complex GP',
    block: 'golaghat_central',
    blockName: 'Golaghat Central Block',
    headquarter: 'Court Field / DC Office',
    lat: 26.5186,
    lng: 93.9688,
    villages: ['Court Field Area', 'Amolapatty', 'Mission Compound', 'Santipur', 'Pulibor'],
    keyLandmarks: 'Golaghat DC Office, SKK Civil Hospital, DR College',
  },
  {
    id: 'gp-bengnakhowa',
    name: 'Bengnakhowa Gaon Panchayat',
    block: 'golaghat_central',
    blockName: 'Golaghat Central Block',
    headquarter: 'Bengnakhowa Chariali',
    lat: 26.5050,
    lng: 93.9600,
    villages: ['Bengnakhowa Gaon', 'Bogidole', 'Dhodar Ali Gaon', 'Charingia'],
    keyLandmarks: 'Bengnakhowa Market, ASTC Bus Terminal, Central Mall Road',
  },
  {
    id: 'gp-furkating',
    name: 'Furkating Gaon Panchayat',
    block: 'golaghat_central',
    blockName: 'Golaghat Central Block',
    headquarter: 'Furkating Station Area',
    lat: 26.4380,
    lng: 93.9850,
    villages: ['Furkating Town', 'Railway Colony', 'Habial Pathar', 'Borahi Gaon'],
    keyLandmarks: 'Furkating Major Railway Junction & Station Bazaar',
  },
  {
    id: 'gp-khumtai',
    name: 'Khumtai Gaon Panchayat',
    block: 'golaghat_central',
    blockName: 'Golaghat Central Block',
    headquarter: 'Khumtai Chariali',
    lat: 26.6120,
    lng: 93.9240,
    villages: ['Khumtai Gaon', 'Borjan Gaon', 'Kothalguri', 'Khatkhati'],
    keyLandmarks: 'Khumtai Weekly Market, Tea Gardens Corridor',
  },
  {
    id: 'gp-dhekial',
    name: 'Dhekial Gaon Panchayat',
    block: 'golaghat_central',
    blockName: 'Golaghat Central Block',
    headquarter: 'Dhekial Chariali',
    lat: 26.5410,
    lng: 93.8950,
    villages: ['Dhekial Gaon', 'Kamarbandha Ali', 'Hatiyekhowa', 'Borbam'],
    keyLandmarks: 'Dhekial Higher Secondary School, Kamarbandha Link',
  },
  {
    id: 'gp-athkhel',
    name: 'Athkhel Gaon Panchayat',
    block: 'golaghat_central',
    blockName: 'Golaghat Central Block',
    headquarter: 'Athkhel Namghar Area',
    lat: 26.4710,
    lng: 93.9310,
    villages: ['Athkhel Gaon', 'Kenduguri', 'Bongal Gaon', 'Mikirbori'],
    keyLandmarks: 'Historic Sri Sri Athkhel Bor Namghar',
  },
  {
    id: 'gp-habial',
    name: 'Habial Gaon Panchayat',
    block: 'golaghat_central',
    blockName: 'Golaghat Central Block',
    headquarter: 'Habial Gaon Center',
    lat: 26.4520,
    lng: 93.9520,
    villages: ['Habial Gaon', 'Doyang Valley Gaon', 'Merapani Road'],
    keyLandmarks: 'Doyang River Corridor, Rural Agricultural Market',
  },
  {
    id: 'gp-ghiladhari',
    name: 'Ghiladhari Gaon Panchayat',
    block: 'golaghat_central',
    blockName: 'Golaghat Central Block',
    headquarter: 'Ghiladhari Ghat',
    lat: 26.4850,
    lng: 93.8720,
    villages: ['Ghiladhari Gaon', 'Kachamari', 'Ghiladhari Pathar'],
    keyLandmarks: 'Ghiladhari River Ghat, Dhodar Ali Link',
  },

  // Dergaon Block
  {
    id: 'gp-dergaon-town',
    name: 'Dergaon Town Gaon Panchayat',
    block: 'dergaon',
    blockName: 'Dergaon Block',
    headquarter: 'Dergaon Chariali',
    lat: 26.7011,
    lng: 93.9723,
    villages: ['Dergaon Chariali', 'Baruahgaon', 'Raja Bahar', 'Borbam'],
    keyLandmarks: 'Assam Police Academy (APTC), Dergaon College, NH-37',
  },
  {
    id: 'gp-negheriting',
    name: 'Negheriting Gaon Panchayat',
    block: 'dergaon',
    blockName: 'Dergaon Block',
    headquarter: 'Negheriting Doul',
    lat: 26.7210,
    lng: 93.9520,
    villages: ['Negheriting Gaon', 'Doul Gaon', 'Brahmaputra Chapori', 'Gelabil'],
    keyLandmarks: 'Historic Negheriting Shiva Doul, Tea Hillocks',
  },
  {
    id: 'gp-missamora',
    name: 'Missamora Gaon Panchayat',
    block: 'dergaon',
    blockName: 'Dergaon Block',
    headquarter: 'Missamora Tiniali',
    lat: 26.6820,
    lng: 93.9120,
    villages: ['Missamora Gaon', 'Baligaon', 'Gohain Gaon', 'Majuli Ferry Link'],
    keyLandmarks: 'Missamora High School, Gelabil River Corridor',
  },
  {
    id: 'gp-dadhara',
    name: 'Dadhara Gaon Panchayat',
    block: 'dergaon',
    blockName: 'Dergaon Block',
    headquarter: 'Dadhara Ali',
    lat: 26.6620,
    lng: 93.9450,
    villages: ['Dadhara Gaon', 'Kakodonga Border', 'Rangamati West'],
    keyLandmarks: 'Dadhara Weekly Bazaar, Kakodonga Bridge',
  },
  {
    id: 'gp-brahmaputra',
    name: 'Brahmaputra Gaon Panchayat',
    block: 'dergaon',
    blockName: 'Dergaon Block',
    headquarter: 'Gelabil Ghat',
    lat: 26.7450,
    lng: 93.9210,
    villages: ['Gelabil River Gaon', 'Bahguri', 'Alengmora Chapori'],
    keyLandmarks: 'Brahmaputra Riverfront & Ferry Point',
  },
  {
    id: 'gp-rangamati',
    name: 'Rangamati Gaon Panchayat',
    block: 'dergaon',
    blockName: 'Dergaon Block',
    headquarter: 'Rangamati Center',
    lat: 26.6540,
    lng: 93.8820,
    villages: ['Rangamati Gaon', 'Puranigudam', 'Chaliha Pathar'],
    keyLandmarks: 'Rangamati Tea Estate & Rural Hospital',
  },

  // Morongi Block
  {
    id: 'gp-morongi',
    name: 'Morongi Gaon Panchayat',
    block: 'morongi',
    blockName: 'Morongi Block',
    headquarter: 'Morongi Purabangla',
    lat: 26.5320,
    lng: 93.8120,
    villages: ['Morongi Gaon', 'Purabangla', 'Khatkhati', 'Tea Division 4'],
    keyLandmarks: 'Morongi Tea Estate, Rangajan Crossing',
  },
  {
    id: 'gp-doigrong',
    name: 'Doigrong Gaon Panchayat',
    block: 'morongi',
    blockName: 'Morongi Block',
    headquarter: 'Doigrong Center',
    lat: 26.5820,
    lng: 93.7820,
    villages: ['Doigrong Gaon', 'Pipeline Colony', 'Bokial'],
    keyLandmarks: 'Doigrong River Bridge, Numaligarh Gas Corridor',
  },
  {
    id: 'gp-ponka',
    name: 'Ponka Gaon Panchayat',
    block: 'morongi',
    blockName: 'Morongi Block',
    headquarter: 'Ponka Chariali',
    lat: 26.5120,
    lng: 93.7650,
    villages: ['Ponka Gaon', 'Letekujan Link', 'Karbi Border Gaon'],
    keyLandmarks: 'Ponka Rural Health Center',
  },
  {
    id: 'gp-letekujan',
    name: 'Letekujan Gaon Panchayat',
    block: 'morongi',
    blockName: 'Morongi Block',
    headquarter: 'Letekujan Tea Gate',
    lat: 26.5450,
    lng: 93.7420,
    villages: ['Letekujan Gaon', 'Numaligarh South', 'Durgapur'],
    keyLandmarks: 'Letekujan Tea Factory & Market',
  },

  // Padumoni Block
  {
    id: 'gp-padumoni',
    name: 'Padumoni Gaon Panchayat',
    block: 'padumoni',
    blockName: 'Padumoni Block',
    headquarter: 'Padumoni Chariali',
    lat: 26.5620,
    lng: 93.9420,
    villages: ['Padumoni Gaon', 'Salmora', 'Dhodar Ali Junction'],
    keyLandmarks: 'Padumoni Tiniali Market & Namghar',
  },
  {
    id: 'gp-adharsattra',
    name: 'Adharsattra Gaon Panchayat',
    block: 'padumoni',
    blockName: 'Padumoni Block',
    headquarter: 'Adharsattra',
    lat: 26.5510,
    lng: 93.9780,
    villages: ['Adharsattra Gaon', 'Kacharihat', 'Kakodonga West'],
    keyLandmarks: 'Historic Adhar Satra, Rural Agricultural Hub',
  },
  {
    id: 'gp-chaliha',
    name: 'Chaliha Gaon Panchayat',
    block: 'padumoni',
    blockName: 'Padumoni Block',
    headquarter: 'Chaliha Gaon',
    lat: 26.5720,
    lng: 93.9120,
    villages: ['Chaliha Gaon', 'Borbam Pathar', 'Dhekial North'],
    keyLandmarks: 'Chaliha High School & Panchayat Bhavan',
  },

  // Sarupathar / Dhansiri Block
  {
    id: 'gp-sarupathar',
    name: 'Sarupathar Town Gaon Panchayat',
    block: 'sarupathar',
    blockName: 'Sarupathar Block',
    headquarter: 'Sarupathar Railway Station',
    lat: 26.1833,
    lng: 93.8167,
    villages: ['Sarupathar Town', 'Daily Bazaar Area', 'Station Road', 'Ward 1-4'],
    keyLandmarks: 'Sarupathar Sub-Divisional Office & Railway Junction',
  },
  {
    id: 'gp-barpathar',
    name: 'Barpathar Gaon Panchayat',
    block: 'sarupathar',
    blockName: 'Sarupathar Block',
    headquarter: 'Barpathar Town Bus Stand',
    lat: 26.3012,
    lng: 93.8645,
    villages: ['Barpathar Town', 'Dhansiri Ghat', 'Borholla Road', 'Tenga Pathar'],
    keyLandmarks: 'Barpathar Town Market, Dhansiri River Bridge',
  },
  {
    id: 'gp-chungajan',
    name: 'Chungajan Gaon Panchayat',
    block: 'sarupathar',
    blockName: 'Sarupathar Block',
    headquarter: 'Chungajan Chariali',
    lat: 26.2410,
    lng: 93.8420,
    villages: ['Chungajan Gaon', 'Border Colony', 'Doyang Valley South'],
    keyLandmarks: 'Chungajan Border Security Point, Weekly Bazaar',
  },
  {
    id: 'gp-naojan',
    name: 'Naojan Gaon Panchayat',
    block: 'sarupathar',
    blockName: 'Sarupathar Block',
    headquarter: 'Naojan Station',
    lat: 26.1120,
    lng: 93.8050,
    villages: ['Naojan Gaon', 'Bilgaon', 'Bokajan Rail Link'],
    keyLandmarks: 'Naojan Railway Station & Dhansiri Forest Border',
  },
  {
    id: 'gp-uriamghat',
    name: 'Uriamghat Gaon Panchayat',
    block: 'sarupathar',
    blockName: 'Sarupathar Block',
    headquarter: 'Uriamghat Market',
    lat: 26.1420,
    lng: 93.8720,
    villages: ['Uriamghat Gaon', 'Chetia Gaon', 'Border Road Sector B'],
    keyLandmarks: 'Uriamghat Border Outpost & Rural Market',
  },
  {
    id: 'gp-bokajan-border',
    name: 'Bokajan Gateway Gaon Panchayat',
    block: 'sarupathar',
    blockName: 'Sarupathar Block',
    headquarter: 'Bokajan Station',
    lat: 26.0167,
    lng: 93.7833,
    villages: ['Bokajan Town', 'Cement Factory Colony', 'Railway Transit Point'],
    keyLandmarks: 'Bokajan Railway Station, Border Transport Hub',
  },

  // Gomariguri / Merapani Block
  {
    id: 'gp-gomariguri',
    name: 'Gomariguri Gaon Panchayat',
    block: 'gomariguri',
    blockName: 'Gomariguri Block',
    headquarter: 'Gomariguri Chariali',
    lat: 26.3820,
    lng: 93.8920,
    villages: ['Gomariguri Gaon', 'Bosa Gaon', 'Dhopabor', 'Fallangani Link'],
    keyLandmarks: 'Gomariguri Higher Secondary School & Market',
  },
  {
    id: 'gp-merapani',
    name: 'Merapani Border Gaon Panchayat',
    block: 'gomariguri',
    blockName: 'Gomariguri Block',
    headquarter: 'Merapani Main Bazaar',
    lat: 26.3310,
    lng: 93.9420,
    villages: ['Merapani Town', 'Border Bazaar Area', 'CRPF Camp Road', 'Doyang West'],
    keyLandmarks: 'Merapani Interstate Commercial Bazaar & Police Outpost',
  },
  {
    id: 'gp-kachomari',
    name: 'Kachomari Gaon Panchayat',
    block: 'gomariguri',
    blockName: 'Gomariguri Block',
    headquarter: 'Kachomari Tiniali',
    lat: 26.4120,
    lng: 93.9120,
    villages: ['Kachomari Gaon', 'Fallangani South', 'Bherbheri'],
    keyLandmarks: 'Kachomari Daily Market & Primary Health Center',
  },
];

export const POPULAR_LOCATIONS = [
  { address: 'Bokakhat Main Chariali (Near NRL Gate)', lat: 26.5925, lng: 93.5937, tag: 'Bokakhat Hub', category: 'town' },
  { address: 'Kohora Kaziranga Safari Gate & Tourist Lodge', lat: 26.5833, lng: 93.4167, tag: 'Kaziranga Range', category: 'tourism' },
  { address: 'Bagori Range Safari Entry, Kaziranga', lat: 26.5710, lng: 93.3520, tag: 'Kaziranga West', category: 'tourism' },
  { address: 'Kaziranga National Orchid & Biodiversity Park', lat: 26.5870, lng: 93.4350, tag: 'Kohora Park', category: 'tourism' },
  { address: 'Numaligarh Refinery (NRL) Main Gate / Tiniali', lat: 26.6347, lng: 93.7431, tag: 'NRL Township', category: 'industry' },
  { address: 'Deopahar Archaeological Heritage Site, Numaligarh', lat: 26.6120, lng: 93.7490, tag: 'Heritage', category: 'tourism' },
  { address: 'Dergaon Police Academy (APTC) & Chariali', lat: 26.7011, lng: 93.9723, tag: 'Dergaon Hub', category: 'town' },
  { address: 'Negheriting Shiva Doul, Dergaon', lat: 26.7210, lng: 93.9520, tag: 'Historic Temple', category: 'tourism' },
  { address: 'Golaghat Town Court Field & DC Office Complex', lat: 26.5186, lng: 93.9688, tag: 'DC Office / Court', category: 'admin' },
  { address: 'Bengnakhowa Chariali & ASTC Bus Stand', lat: 26.5050, lng: 93.9600, tag: 'Golaghat Market', category: 'transit' },
  { address: 'Golaghat SKK Civil Hospital', lat: 26.5240, lng: 93.9720, tag: 'Civil Hospital', category: 'medical' },
  { address: 'Debraj Roy College (DR College), Golaghat', lat: 26.5120, lng: 93.9650, tag: 'College Campus', category: 'education' },
  { address: 'Furkating Railway Junction, Golaghat', lat: 26.4380, lng: 93.9850, landmark: 'Furkating Station', tag: 'Railway Junction', category: 'transit' },
  { address: 'Sarupathar Town & Railway Station', lat: 26.1833, lng: 93.8167, tag: 'Sarupathar Hub', category: 'town' },
  { address: 'Barpathar Town Bus Stand & Daily Bazaar', lat: 26.3012, lng: 93.8645, tag: 'Barpathar Hub', category: 'town' },
  { address: 'Bokajan Railway Station & Border Gateway', lat: 26.0167, lng: 93.7833, tag: 'Bokajan Transit', category: 'transit' },
  { address: 'Kamargaon Chariali, NH-37 Corridor', lat: 26.6210, lng: 93.6820, tag: 'Kamargaon', category: 'transit' },
  { address: 'Khumtai Chariali & Weekly Market', lat: 26.6120, lng: 93.9240, tag: 'Khumtai Hub', category: 'town' },
  { address: 'Morongi Tea Estate / Purabangla Junction', lat: 26.5320, lng: 93.8120, tag: 'Morongi', category: 'tea' },
  { address: 'Halmira Tea Estate & Club Road', lat: 26.4950, lng: 93.9520, tag: 'Halmira', category: 'tea' },
  { address: 'Rangajan Tiniali & NH-39 Crossing', lat: 26.5560, lng: 93.8420, tag: 'NH-39 Junction', category: 'transit' },
  { address: 'Kamarbandha Ali & Dhekial Road', lat: 26.5410, lng: 93.8950, tag: 'Kamarbandha', category: 'town' },
  { address: 'Fallangani Chariali, South Golaghat', lat: 26.4720, lng: 93.8920, tag: 'Fallangani', category: 'town' },
  { address: 'Chungajan Chariali & Border Road', lat: 26.2410, lng: 93.8420, tag: 'Chungajan', category: 'town' }
];
