export interface LocationItem {
  id: string;
  name: string;
  address: string;
  lat: number;
  lng: number;
  city: string;
  region: 'golaghat' | 'jorhat' | 'guwahati' | 'dibrugarh' | 'sivasagar' | 'nagaon' | 'tezpur' | 'dimapur' | 'outstation';
  category: 'town' | 'village' | 'transit' | 'airport' | 'railway' | 'hospital' | 'education' | 'tourism' | 'tea' | 'industry' | 'commercial';
  tag: string;
  landmark?: string;
  popular?: boolean;
}

export const ALL_ASSAM_LOCATIONS: LocationItem[] = [
  // ==========================================
  // GOLAGHAT DISTRICT - TOWNS & MAJOR HUBS
  // ==========================================
  {
    id: 'bkt-main',
    name: 'Bokakhat Main Chariali',
    address: 'Bokakhat Main Chariali, NRL Gate, NH-37, Golaghat, Assam',
    lat: 26.5925,
    lng: 93.5937,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'town',
    tag: 'EASY TRIP HQ',
    landmark: 'Bokakhat Main Chariali / NRL Gate, NH-37',
    popular: true,
  },
  {
    id: 'bkt-hosp',
    name: 'Bokakhat Swahid Kamala Miri Civil Hospital',
    address: 'Bokakhat Civil Hospital Road, Bokakhat, Golaghat, Assam',
    lat: 26.5940,
    lng: 93.5980,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'hospital',
    tag: 'Civil Hospital',
    landmark: 'Near Bokakhat Stadium & Court',
    popular: true,
  },
  {
    id: 'bkt-college',
    name: 'Bokakhat College',
    address: 'Bokakhat College Campus, Bokakhat, Assam',
    lat: 26.5890,
    lng: 93.5910,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'education',
    tag: 'College Campus',
    landmark: 'Bokakhat College Field',
  },
  {
    id: 'bkt-stadium',
    name: 'Bokakhat District Stadium',
    address: 'Bokakhat Stadium Complex, Bokakhat, Assam',
    lat: 26.5960,
    lng: 93.5950,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'town',
    tag: 'Sports Complex',
    landmark: 'Bokakhat Sports Ground',
  },
  {
    id: 'bkt-diffaloo',
    name: 'Diffaloo Pathar / Borjuri',
    address: 'Diffaloo Pathar, Near Bokakhat, Golaghat, Assam',
    lat: 26.5840,
    lng: 93.5620,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'village',
    tag: 'Bokakhat Rural',
    landmark: 'Diffaloo River Bridge',
  },
  {
    id: 'bkt-mohpara',
    name: 'Mohpara Gaon',
    address: 'Mohpara Gaon, Bokakhat Sub-Division, Assam',
    lat: 26.6020,
    lng: 93.6120,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'village',
    tag: 'Village',
    landmark: 'Mohpara LP School',
  },
  {
    id: 'bkt-rajabari',
    name: 'Rajabari Tea Estate & Gaon',
    address: 'Rajabari Tea Estate, Bokakhat, Assam',
    lat: 26.5750,
    lng: 93.5820,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'tea',
    tag: 'Tea Estate',
    landmark: 'Rajabari TE Factory',
  },
  {
    id: 'bkt-panbari',
    name: 'Panbari Reserve & Forest Gate',
    address: 'Panbari Village, Bokakhat, Assam',
    lat: 26.6110,
    lng: 93.5220,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'tourism',
    tag: 'Eco Hub',
    landmark: 'Panbari Forest Beat',
  },
  {
    id: 'bkt-latabari',
    name: 'Latabari Chariali',
    address: 'Latabari Chariali, Bokakhat, Assam',
    lat: 26.5910,
    lng: 93.5780,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'village',
    tag: 'Chariali',
    landmark: 'Latabari Market',
  },
  {
    id: 'bkt-dusutimukh',
    name: 'Dusutimukh Brahmaputra Ghat',
    address: 'Dusutimukh Ghat, Bokakhat, Assam',
    lat: 26.6520,
    lng: 93.5920,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'transit',
    tag: 'River Ghat',
    landmark: 'Dusuti Boat Terminal',
  },

  // ==========================================
  // KAZIRANGA & KOHORA TOURIST BELT
  // ==========================================
  {
    id: 'kzr-kohora',
    name: 'Kohora (Kaziranga Central Range)',
    address: 'Kohora Tourist Complex & Rhino Gate, Kaziranga, Assam',
    lat: 26.5833,
    lng: 93.4167,
    city: 'Kohora',
    region: 'golaghat',
    category: 'tourism',
    tag: 'Kaziranga Safari Gate',
    landmark: 'Kohora Tourist Complex / Rhino Gate',
    popular: true,
  },
  {
    id: 'kzr-orchid',
    name: 'Kaziranga National Orchid & Biodiversity Park',
    address: 'Durgapur, Kohora, Kaziranga National Park, Assam',
    lat: 26.5870,
    lng: 93.4350,
    city: 'Kohora',
    region: 'golaghat',
    category: 'tourism',
    tag: 'Orchid Park',
    landmark: 'Durgapur Orchid Park',
    popular: true,
  },
  {
    id: 'kzr-bagori',
    name: 'Bagori Western Safari Range',
    address: 'Bagori Range Safari Entry, NH-37, Kaziranga, Assam',
    lat: 26.5710,
    lng: 93.3520,
    city: 'Bagori',
    region: 'golaghat',
    category: 'tourism',
    tag: 'Safari Entry',
    landmark: 'Bagori Safari Gate, NH-37',
    popular: true,
  },
  {
    id: 'kzr-agoratoli',
    name: 'Agoratoli Eastern Safari Range',
    address: 'Agoratoli Range Office, Kaziranga, Assam',
    lat: 26.6320,
    lng: 93.5210,
    city: 'Agoratoli',
    region: 'golaghat',
    category: 'tourism',
    tag: 'Eastern Safari',
    landmark: 'Agoratoli Wetland & Jeep Safari Entry',
  },
  {
    id: 'kzr-burapahar',
    name: 'Burapahar (Ghorakati Range)',
    address: 'Burapahar Range Office, NH-37, Assam',
    lat: 26.5610,
    lng: 93.1820,
    city: 'Burapahar',
    region: 'golaghat',
    category: 'tourism',
    tag: 'Trekking & Safari',
    landmark: 'Ghorakati Range Gate',
  },
  {
    id: 'kzr-hatikhuli',
    name: 'Hatikhuli Tea Estate',
    address: 'Hatikhuli Organic Tea Garden, Kohora, Assam',
    lat: 26.5810,
    lng: 93.4420,
    city: 'Kohora',
    region: 'golaghat',
    category: 'tea',
    tag: 'Tea Estate',
    landmark: 'Hatikhuli Factory',
  },
  {
    id: 'kzr-methoni',
    name: 'Methoni Tea Estate',
    address: 'Methoni TE, Near Bokakhat-Kohora Corridor, Assam',
    lat: 26.5860,
    lng: 93.4820,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'tea',
    tag: 'Tea Estate',
    landmark: 'Methoni Club',
  },
  {
    id: 'kzr-golf',
    name: 'Kaziranga Golf Resort & Heritage',
    address: 'Sangsua / Kaziranga Highway, Assam',
    lat: 26.6120,
    lng: 93.5120,
    city: 'Bokakhat',
    region: 'golaghat',
    category: 'tourism',
    tag: 'Luxury Resort',
    landmark: 'Golf Course & Cottages',
  },

  // ==========================================
  // NUMALIGARH & KAMARGAON
  // ==========================================
  {
    id: 'nml-tiniali',
    name: 'Numaligarh Tiniali',
    address: 'Numaligarh Tiniali, NH-37 & NH-39 Junction, Assam',
    lat: 26.6347,
    lng: 93.7431,
    city: 'Numaligarh',
    region: 'golaghat',
    category: 'town',
    tag: 'Major Junction Hub',
    landmark: 'Numaligarh Tiniali / NRL Gateway',
    popular: true,
  },
  {
    id: 'nml-refinery',
    name: 'Numaligarh Refinery (NRL) Main Complex',
    address: 'NRL Refinery Complex, Morangi, Golaghat, Assam',
    lat: 26.5820,
    lng: 93.7820,
    city: 'Numaligarh',
    region: 'golaghat',
    category: 'industry',
    tag: 'Refinery Main Gate',
    landmark: 'NRL Administrative Building & Security Gate',
    popular: true,
  },
  {
    id: 'nml-township',
    name: 'NRL Township (Madhabpur)',
    address: 'Numaligarh Refinery Township, Golaghat, Assam',
    lat: 26.6210,
    lng: 93.7590,
    city: 'Numaligarh',
    region: 'golaghat',
    category: 'town',
    tag: 'NRL Township',
    landmark: 'Delhi Public School (DPS) NRL',
    popular: true,
  },
  {
    id: 'nml-deopahar',
    name: 'Deopahar Archaeological Heritage Site',
    address: 'Deopahar Ruins, Numaligarh, Golaghat, Assam',
    lat: 26.6120,
    lng: 93.7490,
    city: 'Numaligarh',
    region: 'golaghat',
    category: 'tourism',
    tag: 'Historic Heritage',
    landmark: 'Deopahar Hilltop Temple & Sculptures',
    popular: true,
  },
  {
    id: 'kmg-chariali',
    name: 'Kamargaon Chariali',
    address: 'Kamargaon Chariali, NH-37 Corridor, Golaghat, Assam',
    lat: 26.6210,
    lng: 93.6820,
    city: 'Kamargaon',
    region: 'golaghat',
    category: 'town',
    tag: 'Transit Hub',
    landmark: 'Kamargaon College & Market',
    popular: true,
  },
  {
    id: 'kmg-telgaram',
    name: 'Telgaram Chariali',
    address: 'Telgaram, Near Numaligarh, Golaghat, Assam',
    lat: 26.6280,
    lng: 93.7120,
    city: 'Numaligarh',
    region: 'golaghat',
    category: 'village',
    tag: 'Chariali',
    landmark: 'Telgaram Daily Bazaar',
  },
  {
    id: 'kmg-rongbong',
    name: 'Rongbong Gaon & Tea Estate',
    address: 'Rongbong, Numaligarh Corridor, Assam',
    lat: 26.6010,
    lng: 93.7220,
    city: 'Numaligarh',
    region: 'golaghat',
    category: 'tea',
    tag: 'Tea Estate',
    landmark: 'Rongbong ME School',
  },

  // ==========================================
  // DERGAON & SURROUNDINGS
  // ==========================================
  {
    id: 'drg-chariali',
    name: 'Dergaon Chariali',
    address: 'Dergaon Chariali, NH-37, Golaghat, Assam',
    lat: 26.7011,
    lng: 93.9723,
    city: 'Dergaon',
    region: 'golaghat',
    category: 'town',
    tag: 'Dergaon Town Hub',
    landmark: 'Dergaon Chariali / Daily Market',
    popular: true,
  },
  {
    id: 'drg-aptc',
    name: 'Assam Police Training College (APTC) / Academy',
    address: 'Police Training Academy Campus, Dergaon, Assam',
    lat: 26.7090,
    lng: 93.9780,
    city: 'Dergaon',
    region: 'golaghat',
    category: 'education',
    tag: 'Police Academy',
    landmark: 'APTC Main Parade Ground & Campus',
    popular: true,
  },
  {
    id: 'drg-doul',
    name: 'Negheriting Shiva Doul',
    address: 'Negheriting Shiva Doul Hilltop, Dergaon, Assam',
    lat: 26.7210,
    lng: 93.9520,
    city: 'Dergaon',
    region: 'golaghat',
    category: 'tourism',
    tag: 'Historic Temple',
    landmark: 'Ancient Shiva Doul & Tea Garden Hill',
    popular: true,
  },
  {
    id: 'drg-college',
    name: 'Dergaon Kamal Dowerah (DKD) College',
    address: 'DKD College Road, Dergaon, Assam',
    lat: 26.6980,
    lng: 93.9680,
    city: 'Dergaon',
    region: 'golaghat',
    category: 'education',
    tag: 'College Campus',
    landmark: 'DKD College Auditorium',
  },
  {
    id: 'drg-dadhara',
    name: 'Dadhara Tiniali',
    address: 'Dadhara Tiniali, Dergaon, Assam',
    lat: 26.6820,
    lng: 93.9420,
    city: 'Dergaon',
    region: 'golaghat',
    category: 'village',
    tag: 'Tiniali',
    landmark: 'Dadhara High School',
  },
  {
    id: 'drg-badulipar',
    name: 'Badulipar Tiniali',
    address: 'Badulipar Tiniali, NH-37, Golaghat, Assam',
    lat: 26.6620,
    lng: 93.8820,
    city: 'Dergaon',
    region: 'golaghat',
    category: 'village',
    tag: 'NH Junction',
    landmark: 'Badulipar Tea Estate Gate',
  },
  {
    id: 'drg-missamora',
    name: 'Missamora Gaon',
    address: 'Missamora Gaon Panchayat, Dergaon, Assam',
    lat: 26.7320,
    lng: 93.9120,
    city: 'Dergaon',
    region: 'golaghat',
    category: 'village',
    tag: 'Panchayat',
    landmark: 'Missamora High School',
  },
  {
    id: 'drg-khonikar',
    name: 'Khonikar Gaon',
    address: 'Khonikar, Near Negheriting, Dergaon, Assam',
    lat: 26.7150,
    lng: 93.9380,
    city: 'Dergaon',
    region: 'golaghat',
    category: 'village',
    tag: 'Village',
    landmark: 'Khonikar LP School',
  },
  {
    id: 'drg-rangamati',
    name: 'Rangamati Gaon',
    address: 'Rangamati, Dergaon Sub-Division, Assam',
    lat: 26.6890,
    lng: 93.9120,
    city: 'Dergaon',
    region: 'golaghat',
    category: 'village',
    tag: 'Village',
    landmark: 'Rangamati Namghar',
  },

  // ==========================================
  // GOLAGHAT SADAR & CITY BELT
  // ==========================================
  {
    id: 'glt-court',
    name: 'Golaghat Court Field & DC Office',
    address: 'DC Office Complex & Court Field, Golaghat Town, Assam',
    lat: 26.5186,
    lng: 93.9688,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'town',
    tag: 'District HQ / DC Office',
    landmark: 'Golaghat Deputy Commissioner Office',
    popular: true,
  },
  {
    id: 'glt-bengnakhowa',
    name: 'Bengnakhowa Chariali & ASTC Stand',
    address: 'Bengnakhowa Chariali, ASTC Stand, Golaghat, Assam',
    lat: 26.5050,
    lng: 93.9600,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'transit',
    tag: 'Commercial & Bus Stand',
    landmark: 'Bengnakhowa Market & ASTC Bus Terminus',
    popular: true,
  },
  {
    id: 'glt-hospital',
    name: 'Golaghat Swahid Kushal Konwar (SKK) Civil Hospital',
    address: 'SKK Civil Hospital Road, Golaghat Town, Assam',
    lat: 26.5240,
    lng: 93.9720,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'hospital',
    tag: 'Civil Hospital',
    landmark: 'SKK Civil Hospital Complex',
    popular: true,
  },
  {
    id: 'glt-drcollege',
    name: 'Debraj Roy (DR) College',
    address: 'DR College Campus, Circuit House Road, Golaghat, Assam',
    lat: 26.5120,
    lng: 93.9650,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'education',
    tag: 'College Campus',
    landmark: 'DR College Field',
    popular: true,
  },
  {
    id: 'glt-commerce',
    name: 'Golaghat Commerce College',
    address: 'Jyoti Nagar, Golaghat, Assam',
    lat: 26.5290,
    lng: 93.9620,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'education',
    tag: 'Commerce College',
    landmark: 'Jyoti Nagar Campus',
  },
  {
    id: 'glt-furkating',
    name: 'Furkating Railway Junction',
    address: 'Furkating Junction Railway Station, Golaghat, Assam',
    lat: 26.4380,
    lng: 93.9850,
    city: 'Furkating',
    region: 'golaghat',
    category: 'railway',
    tag: 'Major Railway Junction',
    landmark: 'Furkating Station Platform 1 & 2',
    popular: true,
  },
  {
    id: 'glt-khumtai',
    name: 'Khumtai Chariali',
    address: 'Khumtai Chariali, Golaghat, Assam',
    lat: 26.6120,
    lng: 93.9240,
    city: 'Khumtai',
    region: 'golaghat',
    category: 'town',
    tag: 'Khumtai Hub',
    landmark: 'Khumtai Tea Estate & Market',
    popular: true,
  },
  {
    id: 'glt-dhekial',
    name: 'Dhekial Chariali',
    address: 'Dhekial Chariali, Golaghat, Assam',
    lat: 26.5820,
    lng: 93.9350,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'village',
    tag: 'Chariali',
    landmark: 'Dhekial Higher Secondary School',
  },
  {
    id: 'glt-habial',
    name: 'Habial Gaon Panchayat',
    address: 'Habial Gaon, Golaghat, Assam',
    lat: 26.5450,
    lng: 93.9450,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'village',
    tag: 'Gaon Panchayat',
    landmark: 'Habial Namghar',
  },
  {
    id: 'glt-kacharihat',
    name: 'Kacharihat Chariali',
    address: 'Kacharihat, Dhodar Ali Road, Golaghat, Assam',
    lat: 26.5650,
    lng: 93.9850,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'village',
    tag: 'Rural Market',
    landmark: 'Kacharihat Daily Market',
  },
  {
    id: 'glt-adharsattra',
    name: 'Adharsattra Gaon',
    address: 'Historic Adhar Satra, Golaghat, Assam',
    lat: 26.5510,
    lng: 93.9780,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'tourism',
    tag: 'Historic Satra',
    landmark: 'Adhar Satra Namghar',
  },
  {
    id: 'glt-salmora',
    name: 'Salmora Gaon',
    address: 'Salmora Gaon, Padumoni Block, Golaghat, Assam',
    lat: 26.5680,
    lng: 93.9320,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'village',
    tag: 'Village',
    landmark: 'Salmora LP School',
  },
  {
    id: 'glt-kamarbandha',
    name: 'Kamarbandha Ali Chariali',
    address: 'Kamarbandha Ali, Golaghat, Assam',
    lat: 26.5410,
    lng: 93.8950,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'town',
    tag: 'Transit Corridor',
    landmark: 'Kamarbandha Daily Market',
  },
  {
    id: 'glt-rangajan',
    name: 'Rangajan Tiniali (NH-39 Crossing)',
    address: 'Rangajan Tiniali, NH-39, Golaghat, Assam',
    lat: 26.5560,
    lng: 93.8420,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'transit',
    tag: 'NH-39 Crossing',
    landmark: 'Rangajan Forest Beat & Market',
  },
  {
    id: 'glt-morongi',
    name: 'Morongi Tea Estate / Purabangla',
    address: 'Morongi Tea Estate, Golaghat Sadar, Assam',
    lat: 26.5320,
    lng: 93.8120,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'tea',
    tag: 'Tea Corridor',
    landmark: 'Morongi TE Hospital & Purabangla',
  },
  {
    id: 'glt-halmira',
    name: 'Halmira Tea Estate',
    address: 'Halmira Tea Estate, Golaghat, Assam',
    lat: 26.4950,
    lng: 93.9520,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'tea',
    tag: 'Tea Estate',
    landmark: 'Halmira Club & Factory',
  },
  {
    id: 'glt-fallangani',
    name: 'Fallangani Chariali',
    address: 'Fallangani Chariali, South Golaghat, Assam',
    lat: 26.4720,
    lng: 93.8920,
    city: 'Golaghat',
    region: 'golaghat',
    category: 'town',
    tag: 'Rural Hub',
    landmark: 'Fallangani College & Weekly Bazaar',
  },

  // ==========================================
  // DHANSIRI / SARUPATHAR / BARPATHAR / BOKAJAN
  // ==========================================
  {
    id: 'srp-town',
    name: 'Sarupathar Town & Railway Station',
    address: 'Sarupathar Town, Dhansiri Sub-Division, Golaghat, Assam',
    lat: 26.1833,
    lng: 93.8167,
    city: 'Sarupathar',
    region: 'golaghat',
    category: 'town',
    tag: 'Sub-Divisional HQ',
    landmark: 'Sarupathar SDO Office & Station Road',
    popular: true,
  },
  {
    id: 'brp-town',
    name: 'Barpathar Town & Bus Stand',
    address: 'Barpathar Town, Dhansiri Sub-Division, Assam',
    lat: 26.3012,
    lng: 93.8645,
    city: 'Barpathar',
    region: 'golaghat',
    category: 'town',
    tag: 'Town & Market',
    landmark: 'Barpathar Daily Market & Dhansiri Bridge',
    popular: true,
  },
  {
    id: 'chg-chariali',
    name: 'Chungajan Chariali',
    address: 'Chungajan Chariali, Sarupathar, Golaghat, Assam',
    lat: 26.2410,
    lng: 93.8420,
    city: 'Sarupathar',
    region: 'golaghat',
    category: 'town',
    tag: 'Border Hub',
    landmark: 'Chungajan Outpost & Daily Bazaar',
  },
  {
    id: 'nao-station',
    name: 'Naojan Railway Station & Bazaar',
    address: 'Naojan Station Road, Golaghat, Assam',
    lat: 26.1120,
    lng: 93.8050,
    city: 'Sarupathar',
    region: 'golaghat',
    category: 'railway',
    tag: 'Railway Station',
    landmark: 'Naojan Railway Station',
  },
  {
    id: 'uri-market',
    name: 'Uriamghat Border Market',
    address: 'Uriamghat, Dhansiri Sector B, Golaghat, Assam',
    lat: 26.1420,
    lng: 93.8720,
    city: 'Sarupathar',
    region: 'golaghat',
    category: 'village',
    tag: 'Border Market',
    landmark: 'Uriamghat CRPF Camp Road',
  },
  {
    id: 'mrp-bazaar',
    name: 'Merapani Interstate Commercial Bazaar',
    address: 'Merapani Town, Gomariguri Block, Golaghat, Assam',
    lat: 26.3310,
    lng: 93.9420,
    city: 'Merapani',
    region: 'golaghat',
    category: 'town',
    tag: 'Interstate Hub',
    landmark: 'Merapani Police Station & Border Market',
    popular: true,
  },
  {
    id: 'gmr-chariali',
    name: 'Gomariguri Chariali',
    address: 'Gomariguri, Golaghat, Assam',
    lat: 26.3820,
    lng: 93.8920,
    city: 'Gomariguri',
    region: 'golaghat',
    category: 'village',
    tag: 'Block HQ',
    landmark: 'Gomariguri Higher Secondary School',
  },
  {
    id: 'kcm-tiniali',
    name: 'Kachomari Tiniali',
    address: 'Kachomari, Gomariguri, Golaghat, Assam',
    lat: 26.4120,
    lng: 93.9120,
    city: 'Gomariguri',
    region: 'golaghat',
    category: 'village',
    tag: 'Rural Hub',
    landmark: 'Kachomari Primary Health Center',
  },
  {
    id: 'bkj-station',
    name: 'Bokajan Railway Station & Cement Gateway',
    address: 'Bokajan Town, Border Gateway, Karbi Anglong / Golaghat, Assam',
    lat: 26.0167,
    lng: 93.7833,
    city: 'Bokajan',
    region: 'golaghat',
    category: 'railway',
    tag: 'Transit Gateway',
    landmark: 'Bokajan Railway Station & CCI Gate',
    popular: true,
  },

  // ==========================================
  // JORHAT DISTRICT - ALL HUBS & DROP POINTS
  // ==========================================
  {
    id: 'jrh-isbt',
    name: 'Jorhat ISBT (Kotoky Pukhuri)',
    address: 'Jorhat Inter-State Bus Terminus, Kotoky Pukhuri, Jorhat, Assam',
    lat: 26.7580,
    lng: 94.1840,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'transit',
    tag: 'Jorhat ISBT',
    landmark: 'Kotoky Pukhuri ISBT Terminal',
    popular: true,
  },
  {
    id: 'jrh-airport',
    name: 'Jorhat Rowriah Airport (JRH)',
    address: 'Rowriah Airport Road, Jorhat, Assam 785005',
    lat: 26.7319,
    lng: 94.1755,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'airport',
    tag: 'Rowriah Airport',
    landmark: 'Jorhat Airport Terminal & Indian Air Force Station',
    popular: true,
  },
  {
    id: 'jrh-jmch',
    name: 'Jorhat Medical College & Hospital (JMCH)',
    address: 'Kushraj Road, Jail Road, Jorhat, Assam 785001',
    lat: 26.7480,
    lng: 94.2120,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'hospital',
    tag: 'JMCH Hospital',
    landmark: 'JMCH Main Emergency Gate',
    popular: true,
  },
  {
    id: 'jrh-baruah',
    name: 'Baruah Chariali / AT Road Jorhat',
    address: 'Baruah Chariali, AT Road, Jorhat, Assam',
    lat: 26.7530,
    lng: 94.2040,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'town',
    tag: 'City Center',
    landmark: 'Baruah Chariali Flyover & Commercial Area',
    popular: true,
  },
  {
    id: 'jrh-garali',
    name: 'Gar-Ali Commercial Market',
    address: 'Gar-Ali Road, Jorhat City, Assam',
    lat: 26.7545,
    lng: 94.2080,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'commercial',
    tag: 'Shopping Hub',
    landmark: 'Gar-Ali Main Shopping Street',
    popular: true,
  },
  {
    id: 'jrh-station',
    name: 'Jorhat Town Railway Station',
    address: 'Station Road, Tarajan, Jorhat, Assam',
    lat: 26.7510,
    lng: 94.2090,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'railway',
    tag: 'Railway Station',
    landmark: 'Jorhat Town Station Platform',
    popular: true,
  },
  {
    id: 'jrh-aau',
    name: 'Assam Agricultural University (AAU) Borbheta',
    address: 'AAU Campus, Borbheta, Jorhat, Assam',
    lat: 26.7210,
    lng: 94.1950,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'education',
    tag: 'AAU University',
    landmark: 'AAU Main Gate & Directorate',
  },
  {
    id: 'jrh-jec',
    name: 'Jorhat Engineering College (JEC) Garmur',
    address: 'JEC Road, Garmur, Jorhat, Assam',
    lat: 26.7450,
    lng: 94.2480,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'education',
    tag: 'Engineering College',
    landmark: 'JEC Campus & Hostels',
  },
  {
    id: 'jrh-jbcollege',
    name: 'Jagannath Barooah (JB) College',
    address: 'Barpatra Ali, Jorhat, Assam',
    lat: 26.7570,
    lng: 94.2050,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'education',
    tag: 'JB College',
    landmark: 'JB College Auditorium',
  },
  {
    id: 'jrh-nimati',
    name: 'Nimati Ghat (Majuli Ferry Terminal)',
    address: 'Nimati Ghat, Brahmaputra River, Jorhat, Assam',
    lat: 26.8520,
    lng: 94.2540,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'transit',
    tag: 'Ferry Terminal',
    landmark: 'Ro-Pax Ferry Terminal to Majuli Island',
    popular: true,
  },
  {
    id: 'jrh-titabar',
    name: 'Titabar Town & Chariali',
    address: 'Titabar Town, Jorhat District, Assam',
    lat: 26.5890,
    lng: 94.2010,
    city: 'Titabar',
    region: 'jorhat',
    category: 'town',
    tag: 'Town Hub',
    landmark: 'Titabar Daily Bazaar & Railway Station',
    popular: true,
  },
  {
    id: 'jrh-mariani',
    name: 'Mariani Railway Junction',
    address: 'Mariani Junction Railway Station, Jorhat, Assam',
    lat: 26.6620,
    lng: 94.3180,
    city: 'Mariani',
    region: 'jorhat',
    category: 'railway',
    tag: 'Major Railway Hub',
    landmark: 'Mariani Platform 1 & Nagaland Gate',
    popular: true,
  },
  {
    id: 'jrh-teok',
    name: 'Teok Chariali (NH-37)',
    address: 'Teok Chariali, NH-37, Jorhat District, Assam',
    lat: 26.7890,
    lng: 94.4250,
    city: 'Teok',
    region: 'jorhat',
    category: 'town',
    tag: 'NH-37 Junction',
    landmark: 'Teok High School & Tea Corridor',
    popular: true,
  },
  {
    id: 'jrh-kakojan',
    name: 'Kakojan Chariali & College',
    address: 'Kakojan, NH-37, Jorhat, Assam',
    lat: 26.7720,
    lng: 94.3410,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'education',
    tag: 'College & Market',
    landmark: 'Kakojan College Gate',
  },
  {
    id: 'jrh-cinnamara',
    name: 'Cinnamara Tea Estate & Heritage',
    address: 'Cinnamara, Historic 1st Tea Garden, Jorhat, Assam',
    lat: 26.7110,
    lng: 94.2180,
    city: 'Jorhat',
    region: 'jorhat',
    category: 'tea',
    tag: 'Historic Tea Garden',
    landmark: 'Maniram Dewan Heritage Site',
  },

  // ==========================================
  // GUWAHATI METRO - ALL LOCALITIES & TRANSIT
  // ==========================================
  {
    id: 'ghy-airport',
    name: 'Lokpriya Gopinath Bordoloi Airport (GAU / Borjhar)',
    address: 'LGBI Airport Borjhar, VIP Road, Guwahati, Assam 781015',
    lat: 26.1061,
    lng: 91.5859,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'airport',
    tag: 'International Airport',
    landmark: 'LGBI Airport Departure Terminal T1/T2',
    popular: true,
  },
  {
    id: 'ghy-paltan',
    name: 'Guwahati Railway Station (Paltan Bazaar Gate)',
    address: 'Paltan Bazaar, Station Road, Guwahati, Assam 781001',
    lat: 26.1824,
    lng: 91.7516,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'railway',
    tag: 'Main Railway Station',
    landmark: 'Paltan Bazaar Station Entrance & ASTC Stand',
    popular: true,
  },
  {
    id: 'ghy-isbt',
    name: 'ISBT Betkuchi (Inter-State Bus Terminus)',
    address: 'ISBT Complex, NH-27 Bypass, Betkuchi, Guwahati, Assam',
    lat: 26.1180,
    lng: 91.7180,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'transit',
    tag: 'Guwahati ISBT',
    landmark: 'Betkuchi Bus Terminus Main Gate',
    popular: true,
  },
  {
    id: 'ghy-khanapara',
    name: 'Khanapara Flyover & GS Road Entry',
    address: 'Khanapara Chariali, GS Road, Guwahati, Assam',
    lat: 26.1260,
    lng: 91.8150,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'town',
    tag: 'GS Road Gateway',
    landmark: 'Khanapara Veterinary Ground & Flyover',
    popular: true,
  },
  {
    id: 'ghy-sixmile',
    name: 'Six Mile Chariali & VIP Road',
    address: 'Six Mile, GS Road / VIP Road, Guwahati, Assam',
    lat: 26.1360,
    lng: 91.8020,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'town',
    tag: 'Six Mile Flyover',
    landmark: 'Six Mile Signal & Super Market Road',
    popular: true,
  },
  {
    id: 'ghy-dispur',
    name: 'Dispur Assam Capital Secretariat & Super Market',
    address: 'Assam Secretariat Complex, Dispur, Guwahati, Assam',
    lat: 26.1420,
    lng: 91.7910,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'town',
    tag: 'Capital Complex',
    landmark: 'Janata Bhawan / Assam Secretariat Main Gate',
    popular: true,
  },
  {
    id: 'ghy-ganeshguri',
    name: 'Ganeshguri Flyover & Market',
    address: 'Ganeshguri Chariali, GS Road, Guwahati, Assam',
    lat: 26.1520,
    lng: 91.7820,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'commercial',
    tag: 'Commercial Hub',
    landmark: 'Ganesh Mandir & GS Road Shopping Belt',
    popular: true,
  },
  {
    id: 'ghy-jalukbari',
    name: 'Jalukbari Rotunda / Gauhati University Gate',
    address: 'Jalukbari Chariali, NH-27 / NH-17, Guwahati, Assam',
    lat: 26.1480,
    lng: 91.6620,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'education',
    tag: 'Jalukbari Gate',
    landmark: 'Bhupen Hazarika Samadhi Kshetra & GU Main Gate',
    popular: true,
  },
  {
    id: 'ghy-kamakhya',
    name: 'Kamakhya Temple & Railway Station',
    address: 'Nilachal Hill / Kamakhya Station Road, Maligaon, Guwahati, Assam',
    lat: 26.1660,
    lng: 91.7050,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'tourism',
    tag: 'Shaktipeeth Temple',
    landmark: 'Maa Kamakhya Temple Hilltop Gate',
    popular: true,
  },
  {
    id: 'ghy-gmch',
    name: 'Guwahati Medical College & Hospital (GMCH) Bhangagarh',
    address: 'GMCH Complex, Narakasur Hill, Bhangagarh, Guwahati, Assam',
    lat: 26.1580,
    lng: 91.7710,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'hospital',
    tag: 'GMCH Hospital',
    landmark: 'GMCH Emergency & Super Specialty Wing',
    popular: true,
  },
  {
    id: 'ghy-aiims',
    name: 'AIIMS Guwahati (Changsari Campus)',
    address: 'AIIMS Guwahati Campus, Changsari, Kamrup, Assam 781101',
    lat: 26.2480,
    lng: 91.6210,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'hospital',
    tag: 'AIIMS Hospital',
    landmark: 'AIIMS Guwahati Main Hospital Gate',
    popular: true,
  },
  {
    id: 'ghy-maligaon',
    name: 'Maligaon (NF Railway Headquarters)',
    address: 'Maligaon Chariali, Kamrup Metro, Guwahati, Assam',
    lat: 26.1540,
    lng: 91.6890,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'railway',
    tag: 'NFR Headquarters',
    landmark: 'N.F. Railway General Office',
  },
  {
    id: 'ghy-fancybazar',
    name: 'Fancy Bazar Wholesale & Commercial Hub',
    address: 'Fancy Bazar, MG Road, Riverside, Guwahati, Assam',
    lat: 26.1880,
    lng: 91.7410,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'commercial',
    tag: 'Wholesale Market',
    landmark: 'Fancy Bazar Municipal Market & Machkhowa',
  },
  {
    id: 'ghy-chandmari',
    name: 'Chandmari Chariali / Assam Engineering Institute',
    address: 'Chandmari, Guwahati, Assam',
    lat: 26.1860,
    lng: 91.7780,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'town',
    tag: 'Central Guwahati',
    landmark: 'AEI Field & Chandmari Flyover',
  },
  {
    id: 'ghy-beltola',
    name: 'Beltola Daily Bazaar & Survey',
    address: 'Beltola Tiniali, Guwahati, Assam',
    lat: 26.1280,
    lng: 91.7890,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'town',
    tag: 'Beltola Bazaar',
    landmark: 'Beltola Bi-Weekly Organic Market',
  },
  {
    id: 'ghy-panbazar',
    name: 'Panbazar High Court & Cotton University',
    address: 'Panbazar, Guwahati, Assam',
    lat: 26.1890,
    lng: 91.7480,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'education',
    tag: 'Cotton University',
    landmark: 'Cotton University Main Gate & Guwahati High Court',
  },
  {
    id: 'ghy-noonmati',
    name: 'Noonmati Guwahati Refinery (IOCL)',
    address: 'Noonmati, Sector 1, Guwahati, Assam',
    lat: 26.1950,
    lng: 91.8020,
    city: 'Guwahati',
    region: 'guwahati',
    category: 'industry',
    tag: 'IOCL Refinery',
    landmark: 'Guwahati Refinery Gate 1',
  },

  // ==========================================
  // DIBRUGARH DISTRICT - AIRPORT, AMCH & ALL HUBS
  // ==========================================
  {
    id: 'dib-airport',
    name: 'Dibrugarh Mohanbari Airport (DIB)',
    address: 'Mohanbari Airport, Dibrugarh, Assam 786012',
    lat: 27.4839,
    lng: 95.0175,
    city: 'Dibrugarh',
    region: 'dibrugarh',
    category: 'airport',
    tag: 'Airport Terminal',
    landmark: 'Mohanbari Civil Aviation Terminal',
    popular: true,
  },
  {
    id: 'dib-amch',
    name: 'Assam Medical College & Hospital (AMCH) Borbari',
    address: 'AMCH Campus, Borbari, Graham Bazar, Dibrugarh, Assam 786002',
    lat: 27.4680,
    lng: 94.9180,
    city: 'Dibrugarh',
    region: 'dibrugarh',
    category: 'hospital',
    tag: 'AMCH Medical College',
    landmark: 'Historic AMCH Main Emergency Gate',
    popular: true,
  },
  {
    id: 'dib-banipur',
    name: 'Dibrugarh Banipur Railway Station',
    address: 'Banipur Station Road, Dibrugarh, Assam',
    lat: 27.4620,
    lng: 94.9580,
    city: 'Dibrugarh',
    region: 'dibrugarh',
    category: 'railway',
    tag: 'Banipur Station',
    landmark: 'Dibrugarh Main Railway Station Platform',
    popular: true,
  },
  {
    id: 'dib-chowkidinghee',
    name: 'Chowkidinghee Bus Stand & ASTC',
    address: 'Chowkidinghee Chariali, ASTC Stand, Dibrugarh, Assam',
    lat: 27.4780,
    lng: 94.9120,
    city: 'Dibrugarh',
    region: 'dibrugarh',
    category: 'transit',
    tag: 'Central Bus Stand',
    landmark: 'Chowkidinghee Field & ASTC Terminal',
    popular: true,
  },
  {
    id: 'dib-thanachariali',
    name: 'Thana Chariali & New Market',
    address: 'Thana Chariali, Dibrugarh Town, Assam',
    lat: 27.4820,
    lng: 94.9080,
    city: 'Dibrugarh',
    region: 'dibrugarh',
    category: 'commercial',
    tag: 'Town Center',
    landmark: 'Thana Chariali Police Station & Market',
    popular: true,
  },
  {
    id: 'dib-bogibeel',
    name: 'Bogibeel Bridge South Approach',
    address: 'Bogibeel Rail-cum-Road Bridge, Dibrugarh, Assam',
    lat: 27.4020,
    lng: 94.8150,
    city: 'Dibrugarh',
    region: 'dibrugarh',
    category: 'transit',
    tag: 'Brahmaputra Mega Bridge',
    landmark: 'Bogibeel Viewpoint & Highway Toll Plaza',
    popular: true,
  },
  {
    id: 'dib-university',
    name: 'Dibrugarh University Campus',
    address: 'NH-37, Rajabheta, Dibrugarh, Assam',
    lat: 27.4510,
    lng: 94.8980,
    city: 'Dibrugarh',
    region: 'dibrugarh',
    category: 'education',
    tag: 'University Campus',
    landmark: 'Dibrugarh University Main Gate, NH-37',
  },
  {
    id: 'dib-grahambazar',
    name: 'Graham Bazar & Mancotta Road',
    address: 'Graham Bazar, Dibrugarh, Assam',
    lat: 27.4720,
    lng: 94.9150,
    city: 'Dibrugarh',
    region: 'dibrugarh',
    category: 'town',
    tag: 'Mancotta Corridor',
    landmark: 'Mancotta Tea Estate Bungalow & Market',
  },
  {
    id: 'dib-moran',
    name: 'Moran Town & Chariali',
    address: 'Moran Town, NH-37 Corridor, Dibrugarh-Sivasagar Border, Assam',
    lat: 27.1850,
    lng: 94.9320,
    city: 'Moran',
    region: 'dibrugarh',
    category: 'town',
    tag: 'Moran Junction',
    landmark: 'Moran Daily Market & Oil Field Gate',
    popular: true,
  },
  {
    id: 'dib-naharkatia',
    name: 'Naharkatia Town & Tea Hub',
    address: 'Naharkatia Town, Dibrugarh, Assam',
    lat: 27.2840,
    lng: 95.2580,
    city: 'Naharkatia',
    region: 'dibrugarh',
    category: 'town',
    tag: 'Oil & Tea Town',
    landmark: 'Naharkatia Railway Station',
  },
  {
    id: 'dib-chabua',
    name: 'Chabua Town & IAF Air Base Gate',
    address: 'Chabua, NH-37, Dibrugarh, Assam',
    lat: 27.4850,
    lng: 95.1820,
    city: 'Chabua',
    region: 'dibrugarh',
    category: 'town',
    tag: 'Chabua Town',
    landmark: 'Chabua Air Force Gate & Railway Station',
  },
  {
    id: 'dib-duliajan',
    name: 'Duliajan (Oil India Limited Headquarters)',
    address: 'OIL Corporate Headquarters, Duliajan, Dibrugarh, Assam',
    lat: 27.3520,
    lng: 95.3180,
    city: 'Duliajan',
    region: 'dibrugarh',
    category: 'industry',
    tag: 'OIL Headquarters',
    landmark: 'Oil India Limited Field Headquarters Gate',
    popular: true,
  },

  // ==========================================
  // SIVASAGAR & HISTORIC AHOM HERITAGE
  // ==========================================
  {
    id: 'svr-astc',
    name: 'Sivasagar Town & ASTC Bus Stand',
    address: 'ASTC Bus Stand Road, Sivasagar Town, Assam',
    lat: 26.9826,
    lng: 94.6322,
    city: 'Sivasagar',
    region: 'sivasagar',
    category: 'transit',
    tag: 'Sivasagar Central',
    landmark: 'ASTC Stand & Sivasagar Borpukhuri Bank',
    popular: true,
  },
  {
    id: 'svr-rangghar',
    name: 'Historic Rang Ghar & Kareng Ghar',
    address: 'Rang Ghar Complex, Joysagar, Sivasagar, Assam',
    lat: 26.9690,
    lng: 94.6220,
    city: 'Sivasagar',
    region: 'sivasagar',
    category: 'tourism',
    tag: 'Ahom Heritage Amphitheatre',
    landmark: 'Historic Royal Pavilion & Joysagar Tank',
    popular: true,
  },
  {
    id: 'svr-talatal',
    name: 'Talatal Ghar Palace',
    address: 'Talatal Ghar Palace Complex, Rangpur, Sivasagar, Assam',
    lat: 26.9550,
    lng: 94.6280,
    city: 'Sivasagar',
    region: 'sivasagar',
    category: 'tourism',
    tag: 'Historic Royal Palace',
    landmark: 'Talatal Palace Subterranean Base',
  },
  {
    id: 'svr-nazira',
    name: 'Nazira Town & ONGC Assam Asset HQ',
    address: 'Nazira Town, ONGC Colony, Sivasagar, Assam',
    lat: 26.9180,
    lng: 94.7350,
    city: 'Nazira',
    region: 'sivasagar',
    category: 'industry',
    tag: 'ONGC HQ',
    landmark: 'ONGC Assam Asset Officers Club & Complex',
    popular: true,
  },
  {
    id: 'svr-demow',
    name: 'Demow Chariali (NH-37)',
    address: 'Demow Chariali, NH-37, Sivasagar District, Assam',
    lat: 27.1250,
    lng: 94.7480,
    city: 'Demow',
    region: 'sivasagar',
    category: 'town',
    tag: 'NH-37 Town',
    landmark: 'Demow Hospital & Weekly Market',
  },
  {
    id: 'svr-amguri',
    name: 'Amguri Railway Junction & Town',
    address: 'Amguri Town, Sivasagar, Assam',
    lat: 26.8120,
    lng: 94.5320,
    city: 'Amguri',
    region: 'sivasagar',
    category: 'railway',
    tag: 'Amguri Station',
    landmark: 'Amguri Station & Nagaland Border Road',
  },

  // ==========================================
  // NAGAON & KALIABOR
  // ==========================================
  {
    id: 'ngn-town',
    name: 'Nagaon Town Chariali & ASTC',
    address: 'Nagaon Town Chariali, AT Road, Nagaon, Assam',
    lat: 26.3450,
    lng: 92.6840,
    city: 'Nagaon',
    region: 'nagaon',
    category: 'town',
    tag: 'Nagaon Central',
    landmark: 'Nagaon ASTC Bus Stand & Police Reserve Field',
    popular: true,
  },
  {
    id: 'ngn-haibargaon',
    name: 'Haibargaon Railway Station & Commercial',
    address: 'Haibargaon, Nagaon, Assam',
    lat: 26.3580,
    lng: 92.6780,
    city: 'Nagaon',
    region: 'nagaon',
    category: 'railway',
    tag: 'Commercial Hub',
    landmark: 'Haibargaon Station & Wholesale Bazaar',
  },
  {
    id: 'ngn-kaliabor',
    name: 'Kaliabor Tiniali & Kuwaritol',
    address: 'Kaliabor Tiniali, NH-37 Corridor, Nagaon, Assam',
    lat: 26.5410,
    lng: 93.0180,
    city: 'Kaliabor',
    region: 'nagaon',
    category: 'town',
    tag: 'Transit Gate',
    landmark: 'Kuwaritol SDO Office & Tezpur Bridge Road',
    popular: true,
  },
  {
    id: 'ngn-jakhalabandha',
    name: 'Jakhalabandha Railway Station & Chariali',
    address: 'Jakhalabandha, NH-37, Nagaon, Assam',
    lat: 26.5820,
    lng: 93.1250,
    city: 'Jakhalabandha',
    region: 'nagaon',
    category: 'transit',
    tag: 'Kaziranga Transit',
    landmark: 'Jakhalabandha Railway Station & Highway Dhabas',
    popular: true,
  },
  {
    id: 'ngn-samaguri',
    name: 'Samaguri Chariali & Lake View',
    address: 'Samaguri, NH-37, Nagaon, Assam',
    lat: 26.4250,
    lng: 92.8350,
    city: 'Nagaon',
    region: 'nagaon',
    category: 'village',
    tag: 'Highway Corridor',
    landmark: 'Samaguri Beel (Bird Sanctuary)',
  },

  // ==========================================
  // TEZPUR & SONITPUR
  // ==========================================
  {
    id: 'tez-mission',
    name: 'Tezpur Mission Chariali',
    address: 'Mission Chariali, NH-15 / NH-37A, Tezpur, Assam',
    lat: 26.6520,
    lng: 92.7950,
    city: 'Tezpur',
    region: 'tezpur',
    category: 'town',
    tag: 'Tezpur Gateway',
    landmark: 'Mission Chariali Flyover & ASTC Inter-District Gate',
    popular: true,
  },
  {
    id: 'tez-astc',
    name: 'ASTC Tezpur Bus Terminus & Court Chariali',
    address: 'ASTC Bus Stand, Court Chariali, Tezpur, Assam',
    lat: 26.6280,
    lng: 92.7980,
    city: 'Tezpur',
    region: 'tezpur',
    category: 'transit',
    tag: 'Tezpur Town Center',
    landmark: 'Chitralekha Udyan & DC Office Tezpur',
    popular: true,
  },
  {
    id: 'tez-university',
    name: 'Tezpur Central University (Napaam)',
    address: 'Tezpur University Campus, Napaam, Tezpur, Assam 784028',
    lat: 26.7020,
    lng: 92.8320,
    city: 'Tezpur',
    region: 'tezpur',
    category: 'education',
    tag: 'Central University',
    landmark: 'Napaam University Administrative Building',
    popular: true,
  },
  {
    id: 'tez-bridge',
    name: 'Kolia Bhomora Setu (Brahmaputra Bridge)',
    address: 'Kolia Bhomora Bridge Toll Plaza, Tezpur-Nagaon Corridor, Assam',
    lat: 26.6020,
    lng: 92.8620,
    city: 'Tezpur',
    region: 'tezpur',
    category: 'transit',
    tag: 'Brahmaputra Bridge',
    landmark: 'Brahmaputra View Point & Toll Gate',
    popular: true,
  },
  {
    id: 'tez-agnigarh',
    name: 'Agnigarh Historic Heritage Hill',
    address: 'Agnigarh Park, Brahmaputra Bank, Tezpur, Assam',
    lat: 26.6180,
    lng: 92.8050,
    city: 'Tezpur',
    region: 'tezpur',
    category: 'tourism',
    tag: 'Heritage Park',
    landmark: 'Agnigarh Viewpoint & Princess Usha Sculptures',
  },

  // ==========================================
  // DIMAPUR & NAGALAND GATEWAY
  // ==========================================
  {
    id: 'dmp-station',
    name: 'Dimapur Railway Station',
    address: 'Station Road, Dimapur, Nagaland / Assam Border 797112',
    lat: 25.9125,
    lng: 93.7275,
    city: 'Dimapur',
    region: 'dimapur',
    category: 'railway',
    tag: 'Main Junction Station',
    landmark: 'Dimapur Railway Platform 1 & Auto Stand',
    popular: true,
  },
  {
    id: 'dmp-airport',
    name: 'Dimapur Airport (DMU)',
    address: '3rd Mile, Airport Road, Dimapur, Nagaland',
    lat: 25.8839,
    lng: 93.7711,
    city: 'Dimapur',
    region: 'dimapur',
    category: 'airport',
    tag: 'Airport Terminal',
    landmark: 'Dimapur Civil Aviation Terminal',
    popular: true,
  },
  {
    id: 'dmp-puranabazar',
    name: 'Purana Bazar & Highway Crossing',
    address: 'Purana Bazar, NH-29, Dimapur',
    lat: 25.9080,
    lng: 93.7420,
    city: 'Dimapur',
    region: 'dimapur',
    category: 'commercial',
    tag: 'Purana Bazar',
    landmark: 'Zubza / Kohima Highway Junction',
  },
  {
    id: 'dmp-clocktower',
    name: 'Clock Tower & Hong Kong Market',
    address: 'Clock Tower Square, Dimapur City',
    lat: 25.9160,
    lng: 93.7310,
    city: 'Dimapur',
    region: 'dimapur',
    category: 'commercial',
    tag: 'Shopping Hub',
    landmark: 'Clock Tower & Hong Kong Shopping Market',
  },

  // ==========================================
  // TINSUKIA, DIGBOI & UPPER NORTH ASSAM
  // ==========================================
  {
    id: 'tsk-station',
    name: 'Tinsukia Hijuguri Junction Station',
    address: 'Hijuguri, Tinsukia, Assam',
    lat: 27.5020,
    lng: 95.3480,
    city: 'Tinsukia',
    region: 'outstation',
    category: 'railway',
    tag: 'Major Railway Junction',
    landmark: 'New Tinsukia Junction Platform 1',
    popular: true,
  },
  {
    id: 'tsk-town',
    name: 'Tinsukia Daily Bazaar & GNB Road',
    address: 'GNB Road, Tinsukia Town, Assam',
    lat: 27.4920,
    lng: 95.3620,
    city: 'Tinsukia',
    region: 'outstation',
    category: 'commercial',
    tag: 'Commercial Hub',
    landmark: 'Chaliha Nagar & Central Bazaar',
  },
  {
    id: 'dgb-refinery',
    name: 'Digboi Historic Oil Refinery & Museum',
    address: 'Digboi Centenary Oil Museum, Tinsukia, Assam',
    lat: 27.3980,
    lng: 95.6180,
    city: 'Digboi',
    region: 'outstation',
    category: 'industry',
    tag: 'Asia First Oil Well',
    landmark: 'Digboi Centenary Oil Museum & Club',
    popular: true,
  },
  {
    id: 'ddm-town',
    name: 'Doomdooma Tea Capital Town',
    address: 'Doomdooma Chariali, Tinsukia District, Assam',
    lat: 27.5680,
    lng: 95.5720,
    city: 'Doomdooma',
    region: 'outstation',
    category: 'tea',
    tag: 'Tea Capital',
    landmark: 'Doomdooma Daily Market & Club Road',
  },
  {
    id: 'lkh-town',
    name: 'North Lakhimpur Town & Lilabari Airport (IXI)',
    address: 'Lilabari Airport Road / Lakhimpur Town, Assam',
    lat: 27.2340,
    lng: 94.1050,
    city: 'North Lakhimpur',
    region: 'outstation',
    category: 'airport',
    tag: 'North Bank Airport',
    landmark: 'Lilabari Airport Terminal & Lakhimpur Court',
    popular: true,
  },
];

// Fuzzy search and filter helper across all Assam locations
export function searchLocations(
  query: string,
  selectedRegion?: string,
  categoryFilter?: string
): LocationItem[] {
  const cleanQ = (query || '').toLowerCase().trim();

  return ALL_ASSAM_LOCATIONS.filter(item => {
    // Region match if specified
    if (selectedRegion && selectedRegion !== 'all') {
      if (selectedRegion === 'golaghat' && item.region !== 'golaghat') return false;
      if (selectedRegion === 'jorhat' && item.region !== 'jorhat') return false;
      if (selectedRegion === 'guwahati' && item.region !== 'guwahati') return false;
      if (selectedRegion === 'dibrugarh' && item.region !== 'dibrugarh') return false;
      if (selectedRegion === 'outstation' && item.region === 'golaghat') return false;
    }

    // Category filter
    if (categoryFilter && categoryFilter !== 'all') {
      if (categoryFilter === 'transit' && !['transit', 'airport', 'railway'].includes(item.category)) return false;
      if (categoryFilter === 'hospital' && item.category !== 'hospital') return false;
      if (categoryFilter === 'education' && item.category !== 'education') return false;
      if (categoryFilter === 'tourism' && item.category !== 'tourism') return false;
      if (categoryFilter === 'village' && item.category !== 'village') return false;
    }

    // Search query match across multiple fields
    if (!cleanQ) return true;

    const nameMatch = item.name.toLowerCase().includes(cleanQ);
    const addrMatch = item.address.toLowerCase().includes(cleanQ);
    const cityMatch = item.city.toLowerCase().includes(cleanQ);
    const tagMatch = item.tag.toLowerCase().includes(cleanQ);
    const landmarkMatch = item.landmark ? item.landmark.toLowerCase().includes(cleanQ) : false;

    return nameMatch || addrMatch || cityMatch || tagMatch || landmarkMatch;
  });
}

// Coordinate & Address resolver for any arbitrary string
export function findLocationByQuery(query: string): LocationItem | null {
  const q = (query || '').toLowerCase().trim();
  if (!q) return null;

  // 1. Direct exact or substring match in ALL_ASSAM_LOCATIONS
  const directMatch = ALL_ASSAM_LOCATIONS.find(loc => {
    const n = loc.name.toLowerCase();
    const a = loc.address.toLowerCase();
    const c = loc.city.toLowerCase();
    const t = loc.tag.toLowerCase();
    const lm = loc.landmark ? loc.landmark.toLowerCase() : '';
    return n === q || a === q || n.includes(q) || q.includes(n) || c === q || (q.length >= 3 && (t.includes(q) || lm.includes(q)));
  });

  if (directMatch) return directMatch;

  // 2. Sub-word matching (split by space/comma)
  const tokens = q.split(/[\s,]+/).filter(w => w.length > 2);
  for (const token of tokens) {
    const tokenMatch = ALL_ASSAM_LOCATIONS.find(loc => {
      const n = loc.name.toLowerCase();
      const a = loc.address.toLowerCase();
      const c = loc.city.toLowerCase();
      return n.includes(token) || a.includes(token) || c.includes(token);
    });
    if (tokenMatch) return tokenMatch;
  }

  // 3. Fallbacks for key Golaghat / Assam regions
  if (q.includes('bokakhat') || q.includes('bkt') || q.includes('panbari') || q.includes('mohor')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'bkt-main') || null;
  }
  if (q.includes('kaziranga') || q.includes('kohora') || q.includes('bagori') || q.includes('rhino')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'kzr-kohora') || null;
  }
  if (q.includes('numaligarh') || q.includes('nrl') || q.includes('refinery')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'num-town') || null;
  }
  if (q.includes('dergaon') || q.includes('police academy') || q.includes('negheriting')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'drg-chariali') || null;
  }
  if (q.includes('furkating') || q.includes('fkt')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'fkt-junction') || null;
  }
  if (q.includes('sarupathar') || q.includes('barpathar') || q.includes('dhansiri')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'srp-town') || null;
  }
  if (q.includes('golaghat') || q.includes('court') || q.includes('dc office') || q.includes('amulapatty')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'glt-court') || null;
  }
  if (q.includes('jorhat') || q.includes('rowriah') || q.includes('jmch') || q.includes('titabar') || q.includes('mariani') || q.includes('isbt')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'jrh-isbt') || null;
  }
  if (q.includes('guwahati') || q.includes('borjhar') || q.includes('paltan') || q.includes('khanapara') || q.includes('dispur') || q.includes('six mile') || q.includes('gmch') || q.includes('gau')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'ghy-paltan') || null;
  }
  if (q.includes('dibrugarh') || q.includes('mohanbari') || q.includes('amch') || q.includes('bogibeel') || q.includes('moran')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'dib-chowkidinghee') || null;
  }
  if (q.includes('sivasagar') || q.includes('rang ghar') || q.includes('talatal') || q.includes('nazira')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'svr-astc') || null;
  }
  if (q.includes('tezpur') || q.includes('napaam') || q.includes('mission chariali')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'tez-mission') || null;
  }
  if (q.includes('nagaon') || q.includes('kaliabor') || q.includes('jakhalabandha')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'ngn-town') || null;
  }
  if (q.includes('dimapur') || q.includes('nagaland')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'dmp-station') || null;
  }
  if (q.includes('tinsukia') || q.includes('digboi') || q.includes('doomdooma')) {
    return ALL_ASSAM_LOCATIONS.find(l => l.id === 'tsk-station') || null;
  }

  // 4. Fallback: generate pseudo deterministic coordinate in Golaghat region so calculation never fails
  let hash = 0;
  for (let i = 0; i < q.length; i++) {
    hash = (hash << 5) - hash + q.charCodeAt(i);
    hash |= 0;
  }
  const latOffset = ((Math.abs(hash) % 100) / 1000) * 0.4;
  const lngOffset = (((Math.abs(hash) >> 4) % 100) / 1000) * 0.4;

  return {
    id: `custom-${Math.abs(hash)}`,
    name: query,
    address: `${query}, Golaghat District, Assam`,
    lat: 26.5186 + latOffset,
    lng: 93.9688 + lngOffset,
    city: 'Golaghat Region',
    region: 'golaghat',
    category: 'town',
    tag: 'Custom Search Point',
  };
}
